test:
  before_script:
    - sudo apt-get install npm
  script:
    - echo "Navigating to REACT app..."
    - cd visual-prog
    - echo "Installing NPM"
    - npm install
    - echo "Running tests..."
    - npm run test
