image: node:latest

stages:
  - build
  - test

cache:
  paths:
    - /visual-prog/node_modules

dependencies:
  stage: build
  script:
    - cd visual-prog && npm install
    - npm install --save eslint

test:
  stage: test
  script:
    - echo "Navigating to REACT app..."
    - cd visual-prog
    - echo "Running tests..."
    - npm run test
