image: node:latest

stages:
  - build
  - test

cache:
  paths:
    - /node_modules

dependencies:
  stage: build
  script:
    - cd visual-prog && npm install

test:
  stage: test
  before_script:
    - cd visual-prog
    - npm install --save eslint
  script:
    - echo "Navigating to REACT app..."
    - cd visual-prog
    - echo "Running tests..."
    - npm run test
