image: node:latest

stages:
  - build
  - test

dependencies:
  stage: build
  script:
    - npm install

test:
  stage: test
  before_script:
    - npm install --save eslint
  script:
    - echo "Running tests..."
    - npm run test
